// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"
	users "courses-api/businesses/users"

	mock "github.com/stretchr/testify/mock"
)

// Usecase is an autogenerated mock type for the Usecase type
type Usecase struct {
	mock.Mock
}

// Login provides a mock function with given fields: ctx, userDomain
func (_m *Usecase) Login(ctx context.Context, userDomain *users.Domain) (string, error) {
	ret := _m.Called(ctx, userDomain)

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context, *users.Domain) string); ok {
		r0 = rf(ctx, userDomain)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *users.Domain) error); ok {
		r1 = rf(ctx, userDomain)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Register provides a mock function with given fields: ctx, userDomain
func (_m *Usecase) Register(ctx context.Context, userDomain *users.Domain) (users.Domain, error) {
	ret := _m.Called(ctx, userDomain)

	var r0 users.Domain
	if rf, ok := ret.Get(0).(func(context.Context, *users.Domain) users.Domain); ok {
		r0 = rf(ctx, userDomain)
	} else {
		r0 = ret.Get(0).(users.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *users.Domain) error); ok {
		r1 = rf(ctx, userDomain)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewUsecase interface {
	mock.TestingT
	Cleanup(func())
}

// NewUsecase creates a new instance of Usecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUsecase(t mockConstructorTestingTNewUsecase) *Usecase {
	mock := &Usecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
